### ISSUE TITLE
VIP reported as INTERNAL-IP

### ISSUE THREAD

**Issue by dimatha** [siderolabs/cluster-api-bootstrap-provider-talos#137]
Hello guys, 

I'm experimenting with the following components:

Talos 0.14.1
bootstrap-talos  v0.5.2
control-plane-talos  v0.4.4
cluster-api  v1.1.0

`
 controlPlaneConfig:

    init:
      generateType: init
      talosVersion: v0.14
      hostname: 
        source: MachineName
      configPatches:
        - op: add
          path: "/machine/network/interfaces"
          value:
          - interface: eth0
            dhcp: true
            vip:
              ip: 10.11.72.2
        - op: add
          path: /machine/kubelet/nodeIP
          value:
            validSubnets:
            - '10.11.72.0/25'
            - '!10.11.72.2/32'
`

kubectl get nodes -owide:

>NAME                      STATUS   ROLES                  AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE          KERNEL-VERSION   CONTAINER-RUNTIME
dcex1452-talos-cp-4424h   Ready    control-plane,master   45h   v1.22.6   10.11.72.75    <none>        Talos (v0.14.1)   5.15.16-talos    containerd://1.5.8
dcex1452-talos-cp-kmhv8   Ready    control-plane,master   45h   v1.22.6   10.11.72.2     10.11.72.2    Talos (v0.14.1)   5.15.16-talos    containerd://1.5.8
dcex1452-talos-cp-z8v6q   Ready    control-plane,master   45h   v1.22.6   10.11.72.105   <none>        Talos (v0.14.1)   5.15.16-talos    containerd://1.5.8

VIP is reported as INTERNAL-IP & EXTERNAL-IP of the init node

**Comment by dimatha** [comment]
Correct, that’s what I tried to achieve via the patch in the controlPlaneConfig above following the documentation. As you can see VIP is set to 10.11.72.2 and it is excluded in the kubelet nodeIP valid subnets. Or I’m mixing the things?

**Comment by smira** [comment]
The patch looks correct, but it's not clear whether same patch is applied to `controlplane` nodes as well (it should!).

by the way, `init` nodes are deprecated now. if using Sidero, latest version 0.5.0 supports `init`-less templates.

**Comment by andrewrynhard** [comment]
The patch should be in both the `init` and `controlplane` sections.
