### ISSUE TITLE
Option to disable examples in bootstrap config

### ISSUE THREAD

**Issue by Szpadel** [siderolabs/cluster-api-bootstrap-provider-talos#196]
I'm trying to provision talos cluster on Hetzner but hetzner have limitation to max 32KiB for `user_data`
With all comments generated by default this is few hundred bytes too large for control-plane nodes

Could you consider adding option to disable generating comments or change the defaults?
For autogenerated configs comments are not helpful anyway.

**Comment by smira** [comment]
I think this is a regression of some sort.

**Comment by mrkhachaturov** [comment]
@Szpadel can you please share some details of provisining talos on hetzner? 
Are you using bare metal servers or cloud? I am trying to provision on hetzner bare metal.
